// Content for the /services/<slug>/ pages, extracted from the original site.
import type { ServiceDetailPage } from './types';
import { upload } from './site';

export const serviceDetailPages: ServiceDetailPage[] = [
  {
    slug: "brand-product-development",
    meta: { title: "Brand Product Development – Compete Like Pros™", description: "" },
    title: ["Brand & Product", "Development Services"],
    cards: [
      {
        image: upload("/2024/05/Brand.png"),
        subtitle: "BRANDING",
        title: "Services",
        excerpt: "With our support, clients learn new skills, build strong bonds, and take calculated risks to grow. Together, we are purposeful in our pursuit for exce...",
        bio: "With our support, clients learn new skills, build strong bonds, and take calculated risks to grow. Together, we are purposeful in our pursuit for excellence.",
        bioImages: [upload("/2024/05/Brand.png")],
        cta: { label: "LEARN MORE", href: "/services/brand-product-development/" },
        socials: [],
      },
      {
        image: upload("/2024/05/Sales.png"),
        subtitle: "Marketing + Sales",
        title: "Services",
        excerpt: "With our support, clients learn new skills, build strong bonds, and take calculated risks to grow. Together, we are purposeful in our pursuit for exce...",
        bio: "With our support, clients learn new skills, build strong bonds, and take calculated risks to grow. Together, we are purposeful in our pursuit for excellence.",
        bioImages: [upload("/2024/05/Sales.png")],
        cta: { label: "LEARN MORE", href: "/services/brand-product-development/" },
        socials: [],
      },
      {
        image: upload("/2024/05/Web.png"),
        subtitle: "WEBSITE DESIGN +",
        title: "Development",
        excerpt: "With our support, clients learn new skills, build strong bonds, and take calculated risks to grow. Together, we are purposeful in our pursuit for exce...",
        bio: "With our support, clients learn new skills, build strong bonds, and take calculated risks to grow. Together, we are purposeful in our pursuit for excellence.",
        bioImages: [upload("/2024/05/Web.png")],
        cta: { label: "LEARN MORE", href: "/services/brand-product-development/" },
        socials: [],
      },
      {
        image: upload("/2024/05/Product.png"),
        subtitle: "PRODUCT",
        title: "Development",
        excerpt: "With our support, clients learn new skills, build strong bonds, and take calculated risks to grow. Together, we are purposeful in our pursuit for exce...",
        bio: "With our support, clients learn new skills, build strong bonds, and take calculated risks to grow. Together, we are purposeful in our pursuit for excellence.",
        bioImages: [upload("/2024/05/Product.png")],
        cta: { label: "LEARN MORE", href: "/services/brand-product-development/" },
        socials: [],
      },
    ],
    previous: undefined,
    next: { label: "Next Service", title: ["Content Creation", "Licensing"], href: "/services/content-creation-licensing-services/" },
  },
  {
    slug: "content-creation-licensing-services",
    meta: { title: "Content Creation Licensing Services – Compete Like Pros™", description: "" },
    title: ["Content Creation", "/Licensing Services"],
    cards: [
      {
        image: upload("/2024/05/Copywriting.png"),
        subtitle: "COPYWRITING",
        title: "Services",
        excerpt: "With our support, clients learn new skills, build strong bonds, and take calculated risks to grow. Together, we are purposeful in our pursuit for exce...",
        bio: "With our support, clients learn new skills, build strong bonds, and take calculated risks to grow. Together, we are purposeful in our pursuit for excellence.",
        bioImages: [upload("/2024/05/Copywriting.png")],
        cta: { label: "LEARN MORE", href: "/services/content-creation-licensing-services/" },
        socials: [],
      },
      {
        image: upload("/2024/05/Graphic-Design.png"),
        subtitle: "GRAPHIC DESIGN",
        title: "Services",
        excerpt: "With our support, clients learn new skills, build strong bonds, and take calculated risks to grow. Together, we are purposeful in our pursuit for exce...",
        bio: "With our support, clients learn new skills, build strong bonds, and take calculated risks to grow. Together, we are purposeful in our pursuit for excellence.",
        bioImages: [upload("/2024/05/Graphic-Design.png")],
        cta: { label: "LEARN MORE", href: "/services/content-creation-licensing-services/" },
        socials: [],
      },
      {
        image: upload("/2024/05/Weights.png"),
        subtitle: "PHOTOGRAPHY",
        title: "Services",
        excerpt: "With our support, clients learn new skills, build strong bonds, and take calculated risks to grow. Together, we are purposeful in our pursuit for exce...",
        bio: "With our support, clients learn new skills, build strong bonds, and take calculated risks to grow. Together, we are purposeful in our pursuit for excellence.",
        bioImages: [upload("/2024/05/Weights.png")],
        cta: { label: "LEARN MORE", href: "/services/content-creation-licensing-services/" },
        socials: [],
      },
      {
        image: upload("/2024/05/Video.png"),
        subtitle: "VIDEO PHOTOGRAPHY",
        title: "Services",
        excerpt: "With our support, clients learn new skills, build strong bonds, and take calculated risks to grow. Together, we are purposeful in our pursuit for exce...",
        bio: "With our support, clients learn new skills, build strong bonds, and take calculated risks to grow. Together, we are purposeful in our pursuit for excellence.",
        bioImages: [upload("/2024/05/Video.png")],
        cta: { label: "LEARN MORE", href: "/services/content-creation-licensing-services/" },
        socials: [],
      },
    ],
    previous: { label: "Previous Service", title: ["Brand &", "Product Development"], href: "/services/brand-product-development/" },
    next: { label: "Next Service", title: ["Event &", "Project Management"], href: "/services/event-project-management-services/" },
  },
  {
    slug: "event-project-management-services",
    meta: { title: "event-project-management-services - Compete Like Pros™", description: "" },
    title: ["Event & Project", "Management Services"],
    cards: [
      {
        image: upload("/2024/05/Budget.png"),
        subtitle: "Budget Planning /",
        title: "Management",
        excerpt: "With our support, clients learn new skills, build strong bonds, and take calculated risks to grow. Together, we are purposeful in our pursuit for exce...",
        bio: "With our support, clients learn new skills, build strong bonds, and take calculated risks to grow. Together, we are purposeful in our pursuit for excellence.",
        bioImages: [upload("/2024/05/Budget.png")],
        cta: { label: "LEARN MORE", href: "/services/event-project-management-services/" },
        socials: [],
      },
      {
        image: upload("/2024/05/Event.png"),
        subtitle: "Event",
        title: "Management",
        excerpt: "With our support, clients learn new skills, build strong bonds, and take calculated risks to grow. Together, we are purposeful in our pursuit for exce...",
        bio: "With our support, clients learn new skills, build strong bonds, and take calculated risks to grow. Together, we are purposeful in our pursuit for excellence.",
        bioImages: [upload("/2024/05/Event.png")],
        cta: { label: "LEARN MORE", href: "/services/event-project-management-services/" },
        socials: [],
      },
      {
        image: upload("/2024/05/Hotel.png"),
        subtitle: "Housing Selection /",
        title: "Management",
        excerpt: "With our support, clients learn new skills, build strong bonds, and take calculated risks to grow. Together, we are purposeful in our pursuit for exce...",
        bio: "With our support, clients learn new skills, build strong bonds, and take calculated risks to grow. Together, we are purposeful in our pursuit for excellence.",
        bioImages: [upload("/2024/05/Hotel.png")],
        cta: { label: "LEARN MORE", href: "/services/event-project-management-services/" },
        socials: [],
      },
      {
        image: upload("/2024/03/c.jpg"),
        subtitle: "Sponsor",
        title: "Management",
        excerpt: "Sponsor coordination involves identifying and negotiating sponsorship agreements, ensuring sponsor benefits are fulfilled, and managing relationships ...",
        bio: "Sponsor coordination involves identifying and negotiating sponsorship agreements, ensuring sponsor benefits are fulfilled, and managing relationships with sponsors.",
        bioImages: [upload("/2024/03/c.jpg")],
        cta: { label: "LEARN MORE", href: "/services/event-project-management-services/" },
        socials: [],
      },
    ],
    previous: { label: "Previous Service", title: ["Content Creation &", "Licensing"], href: "/services/content-creation-licensing-services/" },
    next: { label: "Next Service", title: ["Fundraising &", "Retailing"], href: "/services/fundraising-retailing-services/" },
  },
  {
    slug: "fundraising-retailing-services",
    meta: { title: "fundraising-retailing-services – Compete Like Pros™", description: "" },
    title: ["Fundraising & Retailing", "Services"],
    cards: [
      {
        image: upload("/2024/05/Direct-Mail.png"),
        subtitle: "Direct Mailing",
        title: "Campaigns",
        excerpt: "In direct marketing, prospects are viewed through a statistical lens, and fundraising considers them as individuals with varying needs; Research sugge...",
        bio: "In direct marketing, prospects are viewed through a statistical lens, and fundraising considers them as individuals with varying needs; Research suggests that interests influence values and preferences.",
        bioImages: [upload("/2024/05/Direct-Mail.png")],
        cta: { label: "LEARN MORE", href: "/services/fundraising-retailing-services/" },
        socials: [],
      },
      {
        image: upload("/2024/05/Fundraiser.png"),
        subtitle: "Earned Income",
        title: "Campaigns",
        excerpt: "Using virtual or in-person fundraising, your organization can host events and sell products for fundraising.",
        bio: "Using virtual or in-person fundraising, your organization can host events and sell products for fundraising.",
        bioImages: [upload("/2024/05/Fundraiser.png")],
        cta: { label: "LEARN MORE", href: "/services/fundraising-retailing-services/" },
        socials: [],
      },
      {
        image: upload("/2024/05/Popup-Shop.png"),
        subtitle: "Popup Shop",
        title: "Campaigns",
        excerpt: "Designed to create a sense of urgency and excitement, these are temporary retail spaces. They feature unique products, collaborations, or experiences ...",
        bio: "Designed to create a sense of urgency and excitement, these are temporary retail spaces. They feature unique products, collaborations, or experiences that cannot be found anywhere else.",
        bioImages: [upload("/2024/05/Popup-Shop.png")],
        cta: { label: "LEARN MORE", href: "/services/fundraising-retailing-services/" },
        socials: [],
      },
      {
        image: upload("/2024/05/Social-Media.png"),
        subtitle: "Social Media",
        title: "Campaigns",
        excerpt: "Designed to create a sense of urgency and excitement, these are temporary retail spaces. They feature unique products, collaborations, or experiences ...",
        bio: "Designed to create a sense of urgency and excitement, these are temporary retail spaces. They feature unique products, collaborations, or experiences that cannot be found anywhere else.",
        bioImages: [upload("/2024/05/Social-Media.png")],
        cta: { label: "LEARN MORE", href: "/services/fundraising-retailing-services/" },
        socials: [],
      },
    ],
    previous: { label: "Previous Service", title: ["Event &", "Project Management"], href: "/services/event-project-management-services/" },
    next: { label: "Next Service", title: ["Procurement &", "Logistics"], href: "/services/procurement-logistics-management/" },
  },
  {
    slug: "procurement-logistics-management",
    meta: { title: "Procurement & Logistics Management Services – Compete Like Pros™", description: "" },
    title: ["Procurement & Logistics", "Management Services"],
    cards: [
      {
        image: upload("/2024/05/Boxes.png"),
        subtitle: "INVENTORY CONTROL",
        title: "Services",
        excerpt: "Our inventory control solutions can help you optimize your business operations. With real-time tracking, accurate forecasting, and efficient managemen...",
        bio: "Our inventory control solutions can help you optimize your business operations. With real-time tracking, accurate forecasting, and efficient management, we reduce costs, prevent stockouts, and maximize profitability.",
        bioImages: [upload("/2024/05/Boxes.png")],
        cta: { label: "LEARN MORE", href: "/services/procurement-logistics-management/" },
        socials: [],
      },
      {
        image: upload("/2024/05/Buyer.png"),
        subtitle: "SOURCING +",
        title: "Purchasing Goods",
        excerpt: "Take advantage of our sourcing and purchasing expertise to streamline your supply chain. To reduce costs and improve efficiency, we identify quality s...",
        bio: "Take advantage of our sourcing and purchasing expertise to streamline your supply chain. To reduce costs and improve efficiency, we identify quality suppliers, negotiate competitive prices, and ensure timely delivery.",
        bioImages: [upload("/2024/05/Buyer.png")],
        cta: { label: "LEARN MORE", href: "/services/procurement-logistics-management/" },
        socials: [],
      },
      {
        image: upload("/2024/07/pexels-efrem-efre-2786187-14393589-scaled.jpg"),
        subtitle: "SHIPPING +",
        title: "Transportation",
        excerpt: "Timely delivery of goods is ensured by efficient transportation and shipping services.",
        bio: "Timely delivery of goods is ensured by efficient transportation and shipping services.",
        bioImages: [upload("/2024/07/pexels-efrem-efre-2786187-14393589-scaled.jpg")],
        cta: { label: "LEARN MORE", href: "/services/procurement-logistics-management/" },
        socials: [],
      },
      {
        image: upload("/2024/05/Manufacturing.png"),
        subtitle: "SUPPLY CHAIN",
        title: "Optimization",
        excerpt: "Utilizing advanced analytics and strategic insights, we optimize supply chains, from procurement to distribution, ensuring efficiency, cost-effectiven...",
        bio: "Utilizing advanced analytics and strategic insights, we optimize supply chains, from procurement to distribution, ensuring efficiency, cost-effectiveness, and resilience.",
        bioImages: [upload("/2024/05/Manufacturing.png")],
        cta: { label: "LEARN MORE", href: "/services/procurement-logistics-management/" },
        socials: [],
      },
    ],
    previous: { label: "Previous Service", title: ["Fundraising &", "Retailing"], href: "/services/fundraising-retailing-services/" },
    next: { label: "Next Service", title: ["Recovery &", "Performance Training"], href: "/services/recovery-performance-training-services/" },
  },
  {
    slug: "recovery-performance-training-services",
    meta: { title: "Recovery & Performance Training Services – Compete Like Pros™", description: "" },
    title: ["Recovery & Performance", "Training Services"],
    // The team widget on the original has no members left, so it shows "No Results Found".
    cards: [],
    previous: { label: "Previous Service", title: ["Procurement &", "Logistics"], href: "/services/procurement-logistics-management/" },
    next: { label: "Next Service", title: ["Sports", "Tourism"], href: "/services/sports-tourism-services/" },
  },
  {
    slug: "sports-tourism-services",
    meta: { title: "Sports Tourism Services - Compete Like Pros™", description: "" },
    title: ["Sports Tourism", "Services"],
    cards: [
      {
        image: upload("/2024/05/Expeience.png"),
        subtitle: "ACTIVITIES PLANNING +",
        title: "Dining",
        excerpt: "Experience the best in sports tourism with our expertly planned activities and dining. A sports fan’s dream trip begins here, with exclusive acc...",
        bio: "Experience the best in sports tourism with our expertly planned activities and dining. A sports fan’s dream trip begins here, with exclusive access to games, stadium tours, and top-rated restaurants.",
        bioImages: [upload("/2024/05/Expeience.png")],
        cta: { label: "LEARN MORE", href: "/services/sports-tourism-services/" },
        socials: [],
      },
      {
        image: upload("/2024/05/money.png"),
        subtitle: "FUNDRAISING",
        title: "Management",
        excerpt: "Ensure a stress-free and unforgettable experience for every sports enthusiast by staying in top-rated accommodations and traveling comfortably with ou...",
        bio: "Ensure a stress-free and unforgettable experience for every sports enthusiast by staying in top-rated accommodations and traveling comfortably with our dedicated services.",
        bioImages: [upload("/2024/05/money.png")],
        cta: { label: "LEARN MORE", href: "/services/sports-tourism-services/" },
        socials: [],
      },
      {
        image: upload("/2024/05/Transportation.png"),
        subtitle: "HOTELS +",
        title: "Logistics",
        excerpt: "Embark on an unforgettable sports tourism experience with our premier venues and game experiences. For a truly unforgettable adventure, you’ll g...",
        bio: "Embark on an unforgettable sports tourism experience with our premier venues and game experiences. For a truly unforgettable adventure, you’ll gain access to top stadiums, VIP seating, and behind-the-scenes tours.",
        bioImages: [upload("/2024/05/Transportation.png")],
        cta: { label: "LEARN MORE", href: "/services/sports-tourism-services/" },
        socials: [],
      },
      {
        image: upload("/2024/05/Venue.png"),
        subtitle: "VENUE & CULTURAL",
        title: "Experiences",
        excerpt: "Embark on an unforgettable sports tourism experience with our premier venues and game experiences. For a truly unforgettable adventure, you’ll g...",
        bio: "Embark on an unforgettable sports tourism experience with our premier venues and game experiences. For a truly unforgettable adventure, you’ll gain access to top stadiums, VIP seating, and behind-the-scenes tours.",
        bioImages: [upload("/2024/05/Venue.png")],
        cta: { label: "LEARN MORE", href: "/services/sports-tourism-services/" },
        socials: [],
      },
    ],
    previous: { label: "Previous Service", title: ["Recovery &", "Performance Training"], href: "/services/recovery-performance-training-services/" },
    next: undefined,
  },
];

export const getServiceDetailPage = (slug: string) => serviceDetailPages.find((p) => p.slug === slug);
