import type { NavItem, SocialLink } from './types';
import localUploads from './local-uploads.json';

export const SITE_URL = 'https://competelikepros.com';

/** Original WordPress uploads folder, used for any file that isn't in public/uploads yet. */
const REMOTE_UPLOADS = process.env.NEXT_PUBLIC_UPLOADS_URL || `${SITE_URL}/wp-content/uploads`;
/** Files present in public/uploads (generated by scripts/sync-uploads.mjs before dev/build). */
const LOCAL_UPLOADS = new Set<string>(localUploads);

/**
 * URL for a WordPress upload, given its path inside wp-content/uploads (e.g. '/2024/03/CLP-Logo-White.png').
 * Served from public/uploads when the original file has been copied there, otherwise from the live site.
 */
export const upload = (path: string) =>
  LOCAL_UPLOADS.has(path) ? `/uploads${path}` : `${REMOTE_UPLOADS}${path}`;

export const site = {
  name: 'Compete Like Pros™',
  logo: {
    light: upload('/2024/03/CLP-Logo-White.png'),
    dark: upload('/2024/04/logoG.png'),
    width: 500,
    height: 226,
  },
  favicon: {
    small: upload('/2024/06/cropped-Clp-browser-32x32.png'),
    large: upload('/2024/06/cropped-Clp-browser-192x192.png'),
    apple: upload('/2024/06/cropped-Clp-browser-180x180.png'),
  },
  menuCopyright: ['Copyright © 2025 Competelikepros.com.', 'All Rights Reserved. | Powered by Soxcessful®'],
  copyright: {
    line: 'Copyright © 2025 Competelikepros.com. All Rights Reserved. Powered by',
    poweredBy: { label: 'Soxcessful®', href: 'https://www.soxcessful.com/' },
    trademark: 'The names and logos of CLP partners are registered and/or common law trademarks. Any unauthorized use is prohibited.',
  },
};

const sports = (base: '/experiences' | '/resources', slugs: Record<string, string>): NavItem[] =>
  Object.entries(slugs).map(([label, slug]) => ({ label, href: `${base}/${slug}/` }));

export const mainNav: NavItem[] = [
  { label: 'Home', href: '/' },
  {
    label: 'EXPERIENCES',
    href: '/experiences/',
    children: sports('/experiences', {
      'For Baseball & Softball': 'baseball',
      'For Basketball': 'basketball-2',
      'For Esports': 'esports',
      'For Fútbol (Soccer)': 'futbol',
      'For Golfing': 'golfing',
      'For Pickleball': 'pickleball',
    }),
  },
  {
    label: 'RESOURCES',
    href: '/resources/',
    children: sports('/resources', {
      'For Baseball & Softball': 'baseball-softball',
      'For Basketball': 'basketball',
      'For Esports': 'esports',
      'For Fútbol (Soccer)': 'futbolsoccer',
      'For Golfing': 'golfing',
      'For Pickleball': 'pickleball',
    }),
  },
  { label: 'SHOP', href: 'https://www.soxcessful.com/Competelikepros', external: true },
  { label: 'UPDATES & NEWS', href: '/updates/' },
  // NextGEN photo-store cart (the checkout lives on the original site).
  { label: 'Cart', href: '/shopping-cart/', icon: 'cart' },
];

export const socialLinks: SocialLink[] = [
  { network: 'instagram', label: 'Instagram', href: 'https://www.instagram.com/competelikepros/' },
  { network: 'linkedin', label: 'LinkedIn', href: 'https://www.linkedin.com/company/competelikepros/' },
  { network: 'facebook', label: 'Facebook', href: 'https://www.facebook.com/competelikepros/' },
  { network: 'x', label: 'X (Twitter)', href: 'https://twitter.com/competelikepros' },
  { network: 'tiktok', label: 'TikTok', href: 'https://www.tiktok.com/@competelikepros' },
  { network: 'youtube', label: 'YouTube', href: 'https://www.youtube.com/@CompeteLikePros' },
];

export const footerLinks: NavItem[][] = [
  [
    { label: 'ABOUT US', href: '/about-us/' },
    { label: 'FAQ', href: 'https://faq.competelikepros.com/' },
    { label: 'PARTNERSHIPS', href: '/partnerships/' },
    { label: 'SHIPPING & RETURNS', href: '/shipping-returns/' },
    { label: 'TERMS AND CONDITIONS', href: '/terms-conditions/' },
  ],
  [
    { label: 'PRIVACY & COOKIES', href: '/privacy-cookies/' },
    { label: 'EXPECTATIONS & COMMITMENT', href: '/our-expectations/' },
    { label: 'CA SUPPLY CHAINS ACT', href: '/ca-supply-chains-act/' },
    { label: 'WAIVER & RELEASE', href: 'https://www.soxcessful.com/waiver-release', external: true },
    { label: 'SMS & EMAIL ALERTS', href: 'https://www.soxcessful.com/sms-emails', external: true },
  ],
];
